In [2]:
#creating an array using numpy library
import numpy as np
a=np.array([1,2,4,3])
print(a)

[1 2 4 3]


In [4]:
#creating more than one dimension
import numpy as np
a=np.array([[1,2],[3,4]])
print('2-d array is:',a)

2-d array is: [[1 2]
 [3 4]]


In [5]:
#dreating with minimum dimensions
import numpy as np
a=np.array([1,2,3,4,5], ndmin=3)
print(a)

[[[1 2 3 4 5]]]


In [6]:
#complexnumber i.e dtype parameter
import numpy as np
a=np.array([1,2,3,4], dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [8]:
#datatypes
import numpy as np
dt = np.dtype(np.int8)
print( dt)

int8


In [10]:
#it is noted that the values int8,int16.... can be stored as i1,i2,....
import numpy as np
dt=np.dtype('i2')
print(dt)

int16


In [11]:
#creating structured datatype
import numpy as np
dt=np.dtype([('marks',np.int8)])
print(dt)

[('marks', 'i1')]


In [12]:
#applying structured datatype to ndarray
import numpy as np
dt=np.dtype([('marks',np.int8)])
a=np.array([(70,),(80,),(90,)], dtype=dt)
print(a)

[(70,) (80,) (90,)]


In [17]:
#shape
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.shape)

(3, 3)


In [19]:
#resizing of the shape
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a.shape=(4,3)
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [23]:
#evenly spaced numbers in an array
import numpy as np
a=np.arange(10)
print('before changing shape')
print(a)
a.ndim
a.shape=(2,5)
print('after changing shape')
print(a)

before changing shape
[0 1 2 3 4 5 6 7 8 9]
after changing shape
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [25]:
#numpy flags
import numpy as np
a=np.array([1,2,3,4,5,6])
print(a.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [26]:
#numpy.empty
import numpy as np
x=np.empty([2,3],dtype=int)
print(x)

[[-1382383376         615           0]
 [          0           1     5111877]]


In [28]:
#numpy.zeroes
import numpy as np
a=np.zeros((5,),dtype=np.int)
print(a)

[0 0 0 0 0]


In [29]:
#numpy.ones
import numpy as np
a=np.ones([2,2],dtype=int)
print(a)

[[1 1]
 [1 1]]


In [30]:
#converting list and tuple to array
import numpy as np
a=[1,2,3]
b=np.asarray(a)
print('List as array')
print(b)
c=(1,2,3,4)
d=np.asarray(c)
print('Tuple as array')
print(d)

List as array
[1 2 3]
Tuple as array
[1 2 3 4]


In [33]:
#creating list object using range function
import numpy as np
l=range(5)
print(l)

range(0, 5)
