In [1]:
#start and stop parameters set
import numpy as np
a=np.arange(10,30,5)
print(a)

[10 15 20 25]


In [2]:
#numpy.logspace
import numpy as np
a=np.logspace(1.0,2.0,num=10)
print(a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [5]:
#indexing and slicing
import numpy as np
a=np.arange(20)
b=a[1:15:3]
print(b)


[ 1  4  7 10 13]


In [9]:
#advanced indexing
import numpy as np
a=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print('Initial array is:')
print(a)
rows=np.array([[0,0],[3,3]])
cols=np.array([[0,2],[0,2]])
y=a[rows,cols]
print('corner elememts:')
print(y)

Initial array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
corner elememts:
[[ 0  2]
 [ 9 11]]


In [10]:
#numpy broadcasting
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([10,20,30,40,50])
c=a*b
print(c)

[ 10  40  90 160 250]


In [11]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([10,11,12])
print('First array:')
print(a)
print('Second array')
print(b)
print('Sum of 2 arrays:')
print(a+b)


First array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Second array
[10 11 12]
Sum of 2 arrays:
[[11 13 15]
 [14 16 18]
 [17 19 21]]


In [15]:
#numpy iterating over an array:
import numpy as np
a=np.arange(0,100,10)
a=a.reshape(2,5)
print('Original array is:')
print(a)
print('Transpose of the original array is:')
b=a.T
print(b)
print('Modified array is:')
for x in np.nditer(b):
    print(x,)

Original array is:
[[ 0 10 20 30 40]
 [50 60 70 80 90]]
Transpose of the original array is:
[[ 0 50]
 [10 60]
 [20 70]
 [30 80]
 [40 90]]
Modified array is:
0
10
20
30
40
50
60
70
80
90
